### ISSUE TITLE
Deploy with GitHub pages.

### ISSUE THREAD

**Issue by hassanShakur** [microhass/portfolio#6]
The portfolio website has been deployed and here is the link 👉 https://microhass.github.io/portfolio/

**Comment by LionRouge1** [comment]
Hi @hassanShakur, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
